FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN npm install
COPY . .
RUN npx prisma generate
EXPOSE 5000
CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
