import { Doctor } from './types';

export const INITIAL_DOCTORS: Doctor[] = [
  { id: '1', name: 'DR. DAVID TAYAH', crm: '12345-AM', specialty: 'Oftalmologia Geral' },
  { id: '2', name: 'DRA. ALINE CANDIDO', crm: '23456-AM', specialty: 'Retina' },
  { id: '3', name: 'DRA. SAMARA QUEIROZ', crm: '34567-AM', specialty: 'Glaucoma' },
  { id: '4', name: 'DRA. ROSEANE BENTES', crm: '45678-AM', specialty: 'Catarata' },
];

export const CATEGORIES: string[] = [
  'SUS',
  'PARTICULAR',
  'UNIMED',
  'D\'SOCIAL',
  'WALDEMIRO LUSTOZA (WPL)',
  'WAIMIRI ATROARI',
];

export const APPOINTMENT_TYPES: string[] = [
  'CONSULTA',
  'RETORNO',
  'TRATAMENTO',
  'AVALIAÇÃO',
];

export const PROCEDURES = [
  { code: '112', name: 'Aspiração' },
  { code: '27', name: 'Avaliação' },
  { code: '68', name: 'Biometria Ultrassônica' },
  { code: '67', name: 'Biomicroscopia de Fundo de Olho' },
  { code: '32', name: 'Calazio' },
  { code: '3', name: 'Campimetria' },
  { code: '37', name: 'Catarata' },
  { code: '119', name: 'Cauterização de Sinal' },
  { code: '38', name: 'Ceratometria' },
  { code: '114', name: 'Ceratoscopia (topografia corneana)' },
  { code: '1', name: 'Consulta' },
  { code: '129', name: 'CTD' },
  { code: '115', name: 'CTD (CDPO) Minimo 3 Medidas' },
  { code: '130', name: 'Exames' },
  { code: '6', name: 'Fundoscopia' },
  { code: '7', name: 'Gonioscopia' },
  { code: '118', name: 'Laudo Endocrinologista' },
  { code: '124', name: 'Laudo Retinologo' },
  { code: '8', name: 'Mapeamento de Retina' },
  { code: '144', name: 'Medicação' },
  { code: '98', name: 'Medir Glicemia' },
  { code: '9', name: 'Microscopia Especular de Cornea' },
  { code: '139', name: 'OCT' },
  { code: '10', name: 'Paquimetria Ultrassonica' },
  { code: '113', name: 'Potencial da Acuidade Visual' },
  { code: '4', name: 'Pterigio' },
  { code: '103', name: 'Receita para Oculos' },
  { code: '99', name: 'Remoção de Ponto' },
  { code: '71', name: 'Remoção de Massa' },
  { code: '48', name: 'Ret Catarata' },
  { code: '111', name: 'Ret de Consulta D\'Social' },
  { code: '54', name: 'Ret Pterigio' },
  { code: '136', name: 'Retinografia' },
  { code: '117', name: 'Retinografia Colorida Binocular' },
  { code: '28', name: 'Retorno' },
  { code: '66', name: 'Retorno (Dilatar)' },
  { code: '107', name: 'Retorno de Cirurgia' },
  { code: '100', name: 'Retorno de Consulta' },
  { code: '104', name: 'Retorno de Yag Laser' },
  { code: '81', name: 'Retorno Laudo' },
  { code: '109', name: 'Retorno para Oculos' },
  { code: '73', name: 'Retorno Remoção de Massa' },
  { code: '116', name: 'Teste de Visao de Cores' },
  { code: '23', name: 'Teste do Olhinho' },
  { code: '137', name: 'Tonometria' },
  { code: '114', name: 'Topografia de Cornea' },
  { code: '51', name: 'Ultrassonografia de Globo Ocular' },
  { code: '101', name: 'Verificar Glicemia' },
  { code: '125', name: 'Visoclin' },
  { code: '106', name: 'Xantelasma' },
  { code: '29', name: 'Yag Laser' },
];
